version: "3.7"

services:
  app:
    container_name: app-todoList
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/frontend"
      - "/frontend/node_modules"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
